#   Mac OS X Intel Universal Makefile
#   Changes:
#   - Dual architecture flags ( i386 + x86_64 )
#   - Compile with base sdk version = 10.5

OPTFLAGS=-O

# don't use -DNDEBUG in order to use MacOSX wxWidgets

ALLFLAGS=-arch i386 -arch x86_64 -mmacosx-version-min=10.5 ${OPTFLAGS}  \
	-DENV_MACOSX \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-D_REENTRANT -DENV_UNIX \
	$(LOCAL_FLAGS)

CXX=c++ $(ALLFLAGS)
CC=cc $(ALLFLAGS)
LINK_SHARED=-bundle

LOCAL_LIBS=-framework CoreFoundation
LOCAL_LIBS_DLL=$(LOCAL_LIBS)

OBJ_CRC32=$(OBJ_CRC32_C)

