#
#   Mac OS X Intel Universal Makefile
#
#   Changes:
#   - Dual architecture flags ( i386 + x86_64 )
#   - Compile with base sdk version = 10.6
#   - Automatic encoding detection using Mozilla's universalchardet library
#

# --------------------------------------
# Mac OS X Specific Flags
# --------------------------------------

MAC_SPECIFIC_FLAGS = -arch i386 -arch x86_64 -mmacosx-version-min=10.6

# --------------------------------------
# Encoding Detection
# --------------------------------------

EXT_LIB_PATH = $(SRC_ROOT_PATH)/../ext-libs
ED_BASE_PATH = $(EXT_LIB_PATH)/universalchardet

ED_C_FLAGS := -I$(ED_BASE_PATH)/src/wrapper/ \
    -I$(ED_BASE_PATH)/src/base/ \
    -I$(ED_BASE_PATH)/src/kludge/ \
    -DDETECT_ENCODING

ED_LIB_FLAGS :=  -L$(ED_BASE_PATH)/build/ -luniversalchardet

# --------------------------------------

OPTFLAGS=-O

# don't use -DNDEBUG in order to use MacOSX wxWidgets
ALLFLAGS= ${OPTFLAGS}  \
	-DENV_MACOSX \
    -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-D_REENTRANT -DENV_UNIX \
	-DNDEBUG \
	$(LOCAL_FLAGS) \
	$(MAC_SPECIFIC_FLAGS) \
	$(ED_C_FLAGS)

CXX=c++ $(ALLFLAGS)
CC=cc $(ALLFLAGS)
LINK_SHARED=-bundle

LOCAL_LIBS=-framework CoreFoundation $(ED_LIB_FLAGS)
LOCAL_LIBS_DLL=$(LOCAL_LIBS)

OBJ_CRC32=$(OBJ_CRC32_C)
